# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.models.incoming_number_list import IncomingNumberList  # noqa: E501
from freeclimb.rest import ApiException


class TestIncomingNumberList(unittest.TestCase):
    """IncomingNumberList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomingNumberList(self):
        """Test IncomingNumberList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = freeclimb.models.incoming_number_list.IncomingNumberList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
