# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.models.buy_incoming_number_request import BuyIncomingNumberRequest  # noqa: E501
from freeclimb.rest import ApiException


class TestBuyIncomingNumberRequest(unittest.TestCase):
    """BuyIncomingNumberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuyIncomingNumberRequest(self):
        """Test BuyIncomingNumberRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = freeclimb.models.buy_incoming_number_request.BuyIncomingNumberRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
