# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.filter_logs_request import FilterLogsRequest  # noqa: E501
from openapi_client.rest import ApiException


class TestFilterLogsRequest(unittest.TestCase):
    """FilterLogsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterLogsRequest(self):
        """Test FilterLogsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.filter_logs_request.FilterLogsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
