# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.recording_list_all_of import RecordingListAllOf  # noqa: E501
from openapi_client.rest import ApiException


class TestRecordingListAllOf(unittest.TestCase):
    """RecordingListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordingListAllOf(self):
        """Test RecordingListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.recording_list_all_of.RecordingListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
