# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.models.update_conference_request import UpdateConferenceRequest  # noqa: E501
from freeclimb.rest import ApiException


class TestUpdateConferenceRequest(unittest.TestCase):
    """UpdateConferenceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateConferenceRequest(self):
        """Test UpdateConferenceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = freeclimb.models.update_conference_request.UpdateConferenceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
