# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.queue_list import QueueList  # noqa: E501
from openapi_client.rest import ApiException


class TestQueueList(unittest.TestCase):
    """QueueList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueList(self):
        """Test QueueList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.queue_list.QueueList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
