# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.models.conference_list import ConferenceList  # noqa: E501
from freeclimb.rest import ApiException


class TestConferenceList(unittest.TestCase):
    """ConferenceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConferenceList(self):
        """Test ConferenceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = freeclimb.models.conference_list.ConferenceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
