# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.models.call_list import CallList  # noqa: E501
from freeclimb.rest import ApiException


class TestCallList(unittest.TestCase):
    """CallList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallList(self):
        """Test CallList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = freeclimb.models.call_list.CallList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
