# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.percl.sms import Sms  # noqa: E501
from freeclimb.rest import ApiException


class TestSms(unittest.TestCase):
    """Sms unit test stubs"""
    to='+12223334444'
    from_number='+13332224444'
    text='Test message'

    def setUp(self):
        self.sms = Sms(to=self.to, from_number=self.from_number, text=self.text)

    def tearDown(self):
        pass

    def testSms(self):
        """Test Sms"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.Sms()  # noqa: E501
        self.assertTrue(isinstance(self.sms, Sms))
        self.assertEqual(self.to, self.sms.to)
        self.assertEqual(self.from_number, self.sms.from_number)
        self.assertEqual(self.text, self.sms.text)
        self.assertTrue(hasattr(self.sms, 'notification_url'))

    def testToDict(self):
        """Test Sms to dictionary"""
        self.assertTrue(isinstance(self.sms.to_dict(), dict))
        self.assertEqual(list(self.sms.to_dict().keys())[0], self.sms.__class__.__name__)


if __name__ == '__main__':
    unittest.main()
