# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import enum

import freeclimb
from freeclimb.percl.language import Language  # noqa: E501
from freeclimb.rest import ApiException


class TestLanguage(unittest.TestCase):
    """Language unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguageSuccess(self):
        """Test Language is successful"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.Language()  # noqa: E501
        self.language = Language('en-AU')
        self.assertTrue(isinstance(self.language, Language))
        self.assertEqual('en-AU', self.language.value)
        self.assertTrue(issubclass(Language, enum.Enum))

    def testLanguageFailure(self):
        """Test Language Fails properly"""
        with self.assertRaises(ValueError):
            Language('NotValidValue')

if __name__ == '__main__':
    unittest.main()
