# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import enum

import freeclimb
from freeclimb.percl.out_dial_if_machine import OutDialIfMachine  # noqa: E501
from freeclimb.rest import ApiException


class TestOutDialIfMachine(unittest.TestCase):
    """OutDialIfMachine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutDialIfMachineSuccess(self):
        """Test OutDialIfMachine is successful"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.OutDialIfMachine()  # noqa: E501
        self.out_dial_if_machine = OutDialIfMachine('hangup')
        self.assertTrue(isinstance(self.out_dial_if_machine, OutDialIfMachine))
        self.assertEqual('hangup', self.out_dial_if_machine.value)
        self.assertTrue(issubclass(OutDialIfMachine, enum.Enum))

    def testOutDialIfMachineFailure(self):
        """Test OutDialIfMachine Fails properly"""
        with self.assertRaises(ValueError):
            OutDialIfMachine('NotValidValue')

if __name__ == '__main__':
    unittest.main()
