# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.percl.get_speech import GetSpeech  # noqa: E501
from freeclimb.rest import ApiException


class TestGetSpeech(unittest.TestCase):
    """GetSpeech unit test stubs"""
    action_url='http://example.com'
    grammar_file='DIG5'

    def setUp(self):
        self.get_speech = GetSpeech(action_url=self.action_url, grammar_file=self.grammar_file)

    def tearDown(self):
        pass

    def testGetSpeech(self):
        """Test GetSpeech"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.GetSpeech()  # noqa: E501
        self.assertTrue(isinstance(self.get_speech, GetSpeech))
        self.assertEqual(self.action_url, self.get_speech.action_url)
        self.assertEqual(self.grammar_file, self.get_speech.grammar_file)
        self.assertTrue(hasattr(self.get_speech, 'grammar_type'))
        self.assertTrue(hasattr(self.get_speech, 'grammar_rule'))
        self.assertTrue(hasattr(self.get_speech, 'play_beep'))
        self.assertTrue(hasattr(self.get_speech, 'no_input_timeout_ms'))
        self.assertTrue(hasattr(self.get_speech, 'recognition_timeout_ms'))
        self.assertTrue(hasattr(self.get_speech, 'confidence_threshold'))
        self.assertTrue(hasattr(self.get_speech, 'n_best_list_length'))
        self.assertTrue(hasattr(self.get_speech, 'sensitivity_level'))
        self.assertTrue(hasattr(self.get_speech, 'speech_complete_timeout_ms'))
        self.assertTrue(hasattr(self.get_speech, 'speech_incomplete_timeout_ms'))
        self.assertTrue(hasattr(self.get_speech, 'prompts'))

    def testAddGrammarType(self):
        """AddGrammarType to conference"""
        grammar_type = 'BUILTIN'
        self.get_speech.grammar_type = freeclimb.GrammarType(grammar_type)
        self.assertTrue(isinstance(self.get_speech.grammar_type, freeclimb.GrammarType))
        self.assertEqual(self.get_speech.grammar_type.value, grammar_type)

    def testToDict(self):
        """Test GetSpeech to dictionary"""
        self.assertTrue(isinstance(self.get_speech.to_dict(), dict))
        self.assertEqual(list(self.get_speech.to_dict().keys())[0], self.get_speech.__class__.__name__)


if __name__ == '__main__':
    unittest.main()
