# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import enum

import freeclimb
from freeclimb.percl.finish_on_key import FinishOnKey  # noqa: E501
from freeclimb.rest import ApiException


class TestFinishOnKey(unittest.TestCase):
    """FinishOnKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinishOnKeySuccess(self):
        """Test FinishOnKey is successful"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.FinishOnKey()  # noqa: E501
        self.finish_on_key = FinishOnKey('1')
        self.assertTrue(isinstance(self.finish_on_key, FinishOnKey))
        self.assertEqual('1', self.finish_on_key.value)
        self.assertTrue(issubclass(FinishOnKey, enum.Enum))

    def testFinishOnKeyFailure(self):
        """Test FinishOnKey Fails properly"""
        with self.assertRaises(ValueError):
            FinishOnKey('NotValidValue')

if __name__ == '__main__':
    unittest.main()
