# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import enum

import freeclimb
from freeclimb.percl.grammar_type import GrammarType  # noqa: E501
from freeclimb.rest import ApiException


class TestGrammarType(unittest.TestCase):
    """GrammarType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrammarTypeSuccess(self):
        """Test GrammarType is successful"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.GrammarType()  # noqa: E501
        self.grammar_type = GrammarType('BUILTIN')
        self.assertTrue(isinstance(self.grammar_type, GrammarType))
        self.assertEqual('BUILTIN', self.grammar_type.value)
        self.assertTrue(issubclass(GrammarType, enum.Enum))

    def testGrammarTypeFailure(self):
        """Test GrammarType Fails properly"""
        with self.assertRaises(ValueError):
            GrammarType('NotValidValue')

if __name__ == '__main__':
    unittest.main()
