# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.percl.play_early_media import PlayEarlyMedia  # noqa: E501
from freeclimb.rest import ApiException


class TestPlayEarlyMedia(unittest.TestCase):
    """PlayEarlyMedia unit test stubs"""
    file='http://example.com/greeting.wav'

    def setUp(self):
        self.play_early_media = PlayEarlyMedia(file=self.file)

    def tearDown(self):
        pass

    def testPlayEarlyMedia(self):
        """Test PlayEarlyMedia"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.PlayEarlyMedia()  # noqa: E501
        self.assertTrue(isinstance(self.play_early_media, PlayEarlyMedia))
        self.assertEqual(self.file, self.play_early_media.file)

    def testToDict(self):
        """Test PlayEarlyMedia to dictionary"""
        self.assertTrue(isinstance(self.play_early_media.to_dict(), dict))
        self.assertEqual(list(self.play_early_media.to_dict().keys())[0], self.play_early_media.__class__.__name__)


if __name__ == '__main__':
    unittest.main()
