# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.percl.hangup import Hangup  # noqa: E501
from freeclimb.rest import ApiException


class TestHangup(unittest.TestCase):
    """Hangup unit test stubs"""

    def setUp(self):
        self.hangup = Hangup()

    def tearDown(self):
        pass

    def testHangup(self):
        """Test Hangup"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.Hangup()  # noqa: E501
        self.assertTrue(isinstance(self.hangup, Hangup))
        self.assertTrue(hasattr(self.hangup, 'call_id'))
        self.assertTrue(hasattr(self.hangup, 'reason'))

    def testToDict(self):
        """Test Hangup to dictionary"""
        self.assertTrue(isinstance(self.hangup.to_dict(), dict))
        self.assertEqual(list(self.hangup.to_dict().keys())[0], self.hangup.__class__.__name__)


if __name__ == '__main__':
    unittest.main()
